
"""
TANFINET – ILL SLA Report Generator
"""
import base64
import calendar
import io
import os
import smtplib
import ssl
from email import encoders
from email.mime.base import MIMEBase
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime
from pathlib import Path

import pandas as pd
import streamlit as st
from dotenv import load_dotenv

DIR = Path(__file__).parent
load_dotenv(DIR / ".env", override=False)

_SMTP_API_KEY = os.environ.get("API_KEY", "")

# ── Page config ────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="TANFINET Report Generator",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Minimalist CSS (Theme Adaptive) ─────────────────────────────────────────
st.markdown("""
<style>
    /* Neutral warm-gray palette */
    .app-header {
        border-bottom: 1px solid #c8c6c3;
        padding-bottom: 1.5rem;
        margin-bottom: 2rem;
    }
    .app-title {
        color: #2e2d2b;
        font-size: 1.75rem;
        font-weight: 600;
        margin: 0;
        letter-spacing: -0.025em;
    }
    .app-subtitle {
        color: #5f5e5b;
        font-size: 0.95rem;
        margin-top: 0.25rem;
    }
    /* Subdued section headers */
    .section-title {
        color: #3a3936;
        font-size: 1.1rem;
        font-weight: 600;
        margin-top: 2rem;
        margin-bottom: 1rem;
        border-bottom: 1px solid #c8c6c3;
        padding-bottom: 0.5rem;
    }
    /* Primary Action Button */
    .stButton > button[kind="primary"] {
        background-color: #5b7fa6;
        color: #ffffff;
        font-weight: 500;
        border-radius: 6px;
        padding: 0.5rem 1rem;
        border: none;
    }
    .stButton > button[kind="primary"]:hover {
        background-color: #4a6d91;
    }
    /* Sidebar neutral tone */
    section[data-testid="stSidebar"] {
        background-color: #e0dedd;
    }
    /* Hide top padding for cleaner look */
    .block-container {
        padding-top: 3rem;
    }
</style>
""", unsafe_allow_html=True)

# ── Header ──────────────────────────────────────────────────────────────────
# Helper function to read the local logo file
def get_image_base64(image_path):
    try:
        with open(image_path, "rb") as img_file:
            return base64.b64encode(img_file.read()).decode()
    except Exception:
        return ""

logo_base64 = get_image_base64("logo2.png")
logo_base64_2 = get_image_base64("logo1.png")

st.markdown(f"""
<div class="app-header" style="
    display: flex;
    align-items: center;
    justify-content: center;
    text-align: left;
    gap: 1.5rem;
    width: 100%;
">
  <img src="data:image/png;base64,{logo_base64_2}" 
       style="width: 70px; height: auto; display: block;">

  <div style="display: flex; flex-direction: column; justify-content: center;">
    <p class="app-title" style="margin: 0; font-size: 1.75rem; font-weight: 600;">TANFINET ILL-SLA Compliance Monitor</p>
    <p class="app-subtitle" style="margin: 0;">Tamil Nadu FibreNet Corporation: Performance Audit Generator</p>
  </div>
    <img src="data:image/png;base64,{logo_base64}" 
       style="width: 110px; height: auto; display: block;">
</div>
""", unsafe_allow_html=True)

# ── Email Helper ───────────────────────────────────────────────────────────
def send_report_email(
    recipients: list,
    report_bytes: bytes,
    report_fname: str,
    report_period: str,
    smtp_host: str,
    smtp_port: int,
    smtp_user: str,
    smtp_password: str,
    smtp_from: str,
    use_ssl: bool = True,
) -> tuple:
    """Send the generated report as an email attachment."""
    try:
        subject = f"TANFINET ILL-SLA Compliance Report — {report_period}"

        body_text = (
            f"Dear Recipient,\n\n"
            f"Please find attached the TANFINET ILL-SLA Compliance Report for {report_period}.\n\n"
            f"This report has been generated by the TANFINET ILL-SLA Compliance Monitor.\n"
            f"For official use only — Tamil Nadu FibreNet Corporation.\n\n"
            f"Regards,\nTANFINET System"
        )

        body_html = f"""
        <html><body style="font-family:Arial,sans-serif;color:#2e2d2b;">
        <table width="600" cellpadding="0" cellspacing="0"
               style="border:1px solid #c8c6c3;border-radius:6px;overflow:hidden;">
          <tr style="background:#0B2447;">
            <td style="padding:18px 24px;">
              <img src="cid:tanfinet_logo" style="height:48px;" alt="TANFINET">
            </td>
          </tr>
          <tr><td style="padding:24px;">
            <h2 style="color:#0B2447;margin:0 0 12px;">ILL-SLA Compliance Report</h2>
            <p style="margin:0 0 8px;">Dear Recipient,</p>
            <p>Please find attached the <strong>TANFINET ILL-SLA Compliance Report</strong>
               for <strong>{report_period}</strong>.</p>
            <p>This report has been generated by the TANFINET ILL-SLA Compliance Monitor.</p>
            <hr style="border:none;border-top:1px solid #c8c6c3;margin:20px 0;">
            <p style="font-size:0.8rem;color:#888581;">
              For official use only — Tamil Nadu FibreNet Corporation.
            </p>
          </td></tr>
        </table>
        </body></html>
        """

        msg_alt = MIMEMultipart("alternative")
        msg_alt.attach(MIMEText(body_text, "plain"))
        msg_alt.attach(MIMEText(body_html, "html"))

        msg_related = MIMEMultipart("related")
        msg_related.attach(msg_alt)

        logo_path = DIR / "logo2.png"
        if logo_path.is_file():
            with open(logo_path, "rb") as _f:
                _img = MIMEImage(_f.read(), "png")
            _img.add_header("Content-ID", "<tanfinet_logo>")
            _img.add_header("Content-Disposition", "inline", filename="logo2.png")
            msg_related.attach(_img)

        # Report attachment
        attachment = MIMEBase("application", "octet-stream")
        attachment.set_payload(report_bytes)
        encoders.encode_base64(attachment)
        attachment.add_header("Content-Disposition", "attachment", filename=report_fname)

        message = MIMEMultipart("mixed")
        message["From"]    = smtp_from
        message["To"]      = ", ".join(recipients)
        message["Subject"] = subject
        message.attach(msg_related)
        message.attach(attachment)

        if use_ssl:
            context = ssl.create_default_context()
            with smtplib.SMTP_SSL(smtp_host, smtp_port, context=context) as server:
                server.login(smtp_user, smtp_password)
                server.sendmail(smtp_from, recipients, message.as_string())
        else:
            with smtplib.SMTP(smtp_host, smtp_port) as server:
                server.ehlo()
                server.starttls(ssl.create_default_context())
                server.login(smtp_user, smtp_password)
                server.sendmail(smtp_from, recipients, message.as_string())

        return True, f"Report sent successfully to: {', '.join(recipients)}"
    except Exception as exc:
        return False, f"Failed to send email: {exc}"


# ── Import report module ────────────────────────────────────────────────────
@st.cache_resource
def _import_report():
    import importlib, sys
    mod_dir = os.path.dirname(os.path.abspath(__file__))
    if mod_dir not in sys.path:
        sys.path.insert(0, mod_dir)
    import report as rpt
    return rpt

rpt = _import_report()

# ═══════════════════════════════════════════════════════════════════════════
#  SIDEBAR
# ═══════════════════════════════════════════════════════════════════════════
with st.sidebar:
    st.markdown("<p style='font-size: 1.1rem; font-weight: 600; color: #2e2d2b;'>Report Settings</p>", unsafe_allow_html=True)
    
    st.markdown("<p style='font-size: 0.85rem; font-weight: 600; color: #5f5e5b; margin-bottom: 0.5rem;'>PERIOD</p>", unsafe_allow_html=True)
    col_m, col_y = st.columns(2)
    with col_m:
        month_num = st.selectbox("Month", range(1, 13), index=2, format_func=lambda m: calendar.month_abbr[m], label_visibility="collapsed")
    with col_y:
        year_val = st.number_input("Year", min_value=2020, max_value=2035, value=2026, step=1, label_visibility="collapsed")
    
    report_period = f"{calendar.month_name[month_num]} {year_val}"
    report_month_start = datetime(int(year_val), int(month_num), 1)

    st.write("")
    with st.expander("Email Settings"):
        smtp_host_val     = st.text_input("SMTP Host",     value="smtp.gmail.com",  key="smtp_host")
        smtp_port_val     = st.number_input("SMTP Port",   min_value=1, max_value=65535, value=465, step=1, key="smtp_port")
        smtp_ssl_val      = st.checkbox("Use SSL (recommended for port 465)", value=True, key="smtp_ssl")
        smtp_from_val     = st.text_input("From Address",  value="admin@msouqllc.com", key="smtp_from")
        smtp_user_val     = st.text_input("SMTP Username", value="admin@msouqllc.com", placeholder="your SMTP login", key="smtp_user")
        smtp_password_val = st.text_input("SMTP Password", value=_SMTP_API_KEY, type="password", key="smtp_password")
        st.caption("Password loaded from `.env` → `API_KEY`. Stored only for this browser session.")

    st.write("")
    with st.expander("Advanced Configuration"):
        random_seed = st.number_input("Random Seed", min_value=0, max_value=9999, value=42, step=1)
        report_format = st.radio("Export Format", ["PDF", "Excel"], horizontal=True)
        _ext = "pdf" if report_format == "PDF" else "xlsx"
        output_fname = st.text_input("Output Filename", value=f"TANFINET_ILL_SLA_{year_val}_{month_num:02d}.{_ext}")

    st.write("")
    st.markdown("<p style='font-size: 0.85rem; font-weight: 600; color: #5f5e5b; margin-bottom: 0.25rem;'>SLA DOCUMENT UPLOAD</p>", unsafe_allow_html=True)
    _dept_names = [name for name, _cid, _cap, _sla in rpt.DEFAULT_DEPARTMENTS]
    sla_dept_selection = st.selectbox(
        "Department",
        options=_dept_names,
        index=0,
    )
    sla_uploaded_file = st.file_uploader(
        "Upload SLA Document",
        type=["pdf", "docx", "doc", "xlsx", "xls", "csv", "txt"],
        help="Upload the SLA reference document for the selected department.",
    )
    if sla_uploaded_file is not None:
        st.caption(f"Loaded: {sla_uploaded_file.name} ({sla_uploaded_file.size / 1024:.1f} KB)")

# ═══════════════════════════════════════════════════════════════════════════
#  MAIN AREA
# ═══════════════════════════════════════════════════════════════════════════

st.markdown('<p class="section-title">Department Configuration</p>', unsafe_allow_html=True)

# Build editable dataframe from defaults
_default_depts = rpt.DEFAULT_DEPARTMENTS
_df_init = pd.DataFrame([
    {"Include": True, "Department Name": name, "Circuit ID": cid, "Capacity (Mbps)": cap, "SLA Target (%)": sla}
    for name, cid, cap, sla in _default_depts
])

if "dept_df" not in st.session_state:
    st.session_state["dept_df"] = _df_init.copy()

# Utility row with state-clearing to prevent checkbox bugs
btn_col1, btn_col2, btn_col3, _ = st.columns([1.5, 1.5, 1.5, 5.5])
with btn_col1:
    if st.button("Select All", use_container_width=True):
        st.session_state["dept_df"]["Include"] = True
        if "dept_editor" in st.session_state: del st.session_state["dept_editor"]
        st.rerun()
with btn_col2:
    if st.button("Deselect All", use_container_width=True):
        st.session_state["dept_df"]["Include"] = False
        if "dept_editor" in st.session_state: del st.session_state["dept_editor"]
        st.rerun()
with btn_col3:
    if st.button("Reset Defaults", use_container_width=True):
        st.session_state["dept_df"] = _df_init.copy()
        if "dept_editor" in st.session_state: del st.session_state["dept_editor"]
        st.rerun()

# Editable table
edited_df = st.data_editor(
    st.session_state["dept_df"],
    use_container_width=True,
    num_rows="fixed",
    column_config={
        "Include": st.column_config.CheckboxColumn("Include", width="small"),
        "Department Name": st.column_config.TextColumn("Department Name", width="large", disabled=True),
        "Circuit ID": st.column_config.TextColumn("Circuit ID", width="medium", disabled=True),
        "Capacity (Mbps)": st.column_config.NumberColumn("Capacity (Mbps)", min_value=1, max_value=100_000, step=50, width="medium"),
        "SLA Target (%)": st.column_config.NumberColumn("SLA Target (%)", min_value=90.0, max_value=99.99, step=0.5, format="%.2f %%", width="medium"),
    },
    key="dept_editor",
    hide_index=True,
)

# Selection summary based on the output of the data_editor
selected = edited_df[edited_df["Include"] == True]   
n_sel = len(selected)

st.write("")
m1, m2, m3 = st.columns(3)
m1.metric("Selected Departments", n_sel)
m2.metric("Reporting Period", report_period)
m3.metric("Total Contracted BW", f"{int(selected['Capacity (Mbps)'].sum()):,} Mbps" if n_sel else "—")

# ═══════════════════════════════════════════════════════════════════════════
#  EXCEL REPORT BUILDER
# ═══════════════════════════════════════════════════════════════════════════

def build_excel_report(departments, report_period, report_month_start, random_seed=42):
    """Build an Excel workbook with Summary, Daily Bandwidth, and Outages sheets."""
    import calendar as cal
    import openpyxl
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    from openpyxl.utils import get_column_letter

    dept_rows, total, compliant, breach, overall = rpt.prepare_data(
        departments, report_month_start, random_seed=random_seed
    )
    num_days = cal.monthrange(report_month_start.year, report_month_start.month)[1]

    wb = openpyxl.Workbook()

    # ── Shared styles ────────────────────────────────────────────────────
    hdr_fill   = PatternFill("solid", fgColor="0B2447")
    hdr_font   = Font(bold=True, color="FFFFFF", size=10)
    title_font = Font(bold=True, size=13, color="0B2447")
    ok_fill    = PatternFill("solid", fgColor="D5F5E3")
    fail_fill  = PatternFill("solid", fgColor="FADBD8")
    ok_font    = Font(bold=True, color="1E8449", size=9)
    fail_font  = Font(bold=True, color="C0392B", size=9)
    center     = Alignment(horizontal="center", vertical="center", wrap_text=True)
    left       = Alignment(horizontal="left",   vertical="center", wrap_text=True)
    thin       = Side(style="thin", color="CDD5E0")
    border     = Border(left=thin, right=thin, top=thin, bottom=thin)

    def set_header_row(ws, row_num, cols):
        for ci, val in enumerate(cols, 1):
            c = ws.cell(row=row_num, column=ci, value=val)
            c.fill, c.font, c.alignment, c.border = hdr_fill, hdr_font, center, border

    # ── Sheet 1: Summary ─────────────────────────────────────────────────
    ws1 = wb.active
    ws1.title = "Summary"
    ws1.row_dimensions[1].height = 22
    ws1.row_dimensions[2].height = 14

    ws1["A1"] = f"TANFINET ILL-SLA Compliance Report — {report_period}"
    ws1["A1"].font = title_font
    ws1["A1"].alignment = left
    ws1.merge_cells("A1:J1")

    ws1["A2"] = f"Generated: {datetime.now().strftime('%d %b %Y, %H:%M')}"
    ws1["A2"].font = Font(italic=True, size=9, color="888581")
    ws1.merge_cells("A2:J2")

    # KPI summary row
    kpi_labels = ["Total Depts", str(total), "Compliant", str(compliant),
                  "Breach", str(breach), "Overall Uptime", f"{overall:.3f}%", "", ""]
    for ci, val in enumerate(kpi_labels, 1):
        c = ws1.cell(row=4, column=ci, value=val)
        c.font = Font(bold=(ci % 2 == 1), size=9, color="0B2447" if ci % 2 == 1 else "000000")
        c.alignment = center

    # Department compliance table
    tbl_headers = ["Department", "Circuit ID", "Capacity (Mbps)", "SLA Target (%)",
                   "Achieved (%)", "Status", "Avg BW (Mbps)", "Peak BW (Mbps)",
                   "95th Pctile (Mbps)", "Downtime (min)"]
    set_header_row(ws1, 6, tbl_headers)

    for ri, d in enumerate(dept_rows, 7):
        row_vals = [d["name"], d["circuit_id"], d["capacity"], d["sla"],
                    d["achieved"], d["status"], d["avg_bw"], d["peak_bw"],
                    d["p95_bw"], d["down_min"]]
        for ci, val in enumerate(row_vals, 1):
            cell = ws1.cell(row=ri, column=ci, value=val)
            cell.border = border
            cell.alignment = left if ci == 1 else center
            if ci == 6:
                cell.fill = ok_fill if val == "COMPLIANT" else fail_fill
                cell.font = ok_font if val == "COMPLIANT" else fail_font

    for i, w in enumerate([30, 16, 16, 14, 14, 14, 16, 16, 18, 15], 1):
        ws1.column_dimensions[get_column_letter(i)].width = w
    ws1.freeze_panes = "A7"

    # ── Sheet 2: Daily Bandwidth ─────────────────────────────────────────
    ws2 = wb.create_sheet("Daily Bandwidth")
    day_headers = ["Day"] + [d["name"] for d in dept_rows]
    set_header_row(ws2, 1, day_headers)
    for day in range(num_days):
        for ci, val in enumerate([day + 1] + [d["bw_series"][day] for d in dept_rows], 1):
            cell = ws2.cell(row=day + 2, column=ci, value=val)
            cell.border = border
            cell.alignment = center
    ws2.column_dimensions["A"].width = 8
    for i in range(2, len(dept_rows) + 2):
        ws2.column_dimensions[get_column_letter(i)].width = 22
    ws2.freeze_panes = "B2"

    # ── Sheet 3: Outages ─────────────────────────────────────────────────
    ws3 = wb.create_sheet("Outages")
    set_header_row(ws3, 1, ["Department", "Timestamp", "Duration (min)", "Cause", "Resolved"])
    ri = 2
    for d in dept_rows:
        for o in d["outages"]:
            for ci, val in enumerate([d["name"], o["ts"], o["dur"], o["cause"], o["res"]], 1):
                cell = ws3.cell(row=ri, column=ci, value=val)
                cell.border = border
                cell.alignment = left if ci in (1, 4) else center
            ri += 1
    for i, w in enumerate([30, 22, 16, 28, 10], 1):
        ws3.column_dimensions[get_column_letter(i)].width = w

    buf = io.BytesIO()
    wb.save(buf)
    buf.seek(0)
    return buf.read()


st.markdown('<p class="section-title">Report Generation</p>', unsafe_allow_html=True)

if n_sel == 0:
    st.error("Select at least one department to generate a report.")
else:
    generate_col, _ = st.columns([2, 6])
    with generate_col:
        _gen_label = "Generate Excel Report" if report_format == "Excel" else "Generate PDF Report"
        generate_btn = st.button(_gen_label, type="primary", use_container_width=True)

    if generate_btn:
        departments = [
            (row["Department Name"], row["Circuit ID"], int(row["Capacity (Mbps)"]), float(row["SLA Target (%)"]))
            for _, row in selected.iterrows()
        ]

        try:
            if report_format == "PDF":
                with st.spinner("Compiling PDF..."):
                    file_bytes = rpt.build_report(
                        output=None,
                        departments=departments,
                        report_period=report_period,
                        report_month_start=report_month_start,
                        random_seed=int(random_seed),
                        logo1_path=None,
                        logo2_path=None,
                    )
                file_mime = "application/pdf"
            else:
                with st.spinner("Building Excel workbook..."):
                    file_bytes = build_excel_report(
                        departments=departments,
                        report_period=report_period,
                        report_month_start=report_month_start,
                        random_seed=int(random_seed),
                    )
                file_mime = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"

            st.session_state["report_bytes"] = file_bytes
            st.session_state["report_fname"] = output_fname
            st.session_state["report_mime"]  = file_mime

            # Append to history
            if "report_history" not in st.session_state:
                st.session_state["report_history"] = []
            st.session_state["report_history"].insert(0, {
                "fname":        output_fname,
                "period":       report_period,
                "format":       report_format,
                "generated_at": datetime.now().strftime("%d %b %Y, %H:%M"),
                "size_kb":      round(len(file_bytes) / 1024, 1),
                "bytes":        file_bytes,
                "mime":         file_mime,
            })

        except Exception as e:
            st.error(f"Error generating report: {e}")

    # Persisted Download Button
    if "report_bytes" in st.session_state:
        dl_col, _ = st.columns([2, 6])
        with dl_col:
            _dl_ext = st.session_state['report_fname'].split('.')[-1].upper()
            _dl_label = "Download Excel Report" if _dl_ext == "XLSX" else "Download PDF Report"
            st.download_button(
                label=_dl_label,
                data=st.session_state["report_bytes"],
                file_name=st.session_state["report_fname"],
                mime=st.session_state["report_mime"],
                use_container_width=True,
            )
        st.caption(f"File: {st.session_state['report_fname']} ({len(st.session_state['report_bytes']) / 1024:.0f} KB)")

# ═══════════════════════════════════════════════════════════════════════════
#  SEND VIA EMAIL
# ═══════════════════════════════════════════════════════════════════════════
if "report_bytes" in st.session_state:
    st.markdown('<p class="section-title">Send Report via Email</p>', unsafe_allow_html=True)

    _email_col1, _email_col2 = st.columns([4, 2])
    with _email_col1:
        _email_to_raw = st.text_input(
            "Recipient Email(s)",
            placeholder="user@example.com, another@example.com",
            help="Separate multiple addresses with commas.",
            label_visibility="collapsed",
            key="email_to_input",
        )
    with _email_col2:
        _send_btn = st.button("Send Report", use_container_width=True, key="send_email_btn")

    if _send_btn:
        _recipients = [e.strip() for e in _email_to_raw.split(",") if e.strip()]
        _host     = st.session_state.get("smtp_host",     "")
        _port     = int(st.session_state.get("smtp_port",  465))
        _use_ssl  = bool(st.session_state.get("smtp_ssl",  True))
        _from     = st.session_state.get("smtp_from",     "")
        _user     = st.session_state.get("smtp_user",     "")
        _pwd      = st.session_state.get("smtp_password", "")

        _missing = []
        if not _recipients: _missing.append("Recipient Email(s)")
        if not _host:       _missing.append("SMTP Host (Email Settings)")
        if not _from:       _missing.append("From Address (Email Settings)")
        if not _user:       _missing.append("SMTP Username (Email Settings)")
        if not _pwd:        _missing.append("SMTP Password (Email Settings)")

        if _missing:
            st.warning("Please provide the following before sending:\n- " + "\n- ".join(_missing))
        else:
            with st.spinner(f"Sending to {', '.join(_recipients)}…"):
                _ok, _msg = send_report_email(
                    recipients    = _recipients,
                    report_bytes  = st.session_state["report_bytes"],
                    report_fname  = st.session_state["report_fname"],
                    report_period = report_period,
                    smtp_host     = _host,
                    smtp_port     = _port,
                    smtp_user     = _user,
                    smtp_password = _pwd,
                    smtp_from     = _from,
                    use_ssl       = _use_ssl,
                )
            if _ok:
                st.success(_msg)
            else:
                st.error(_msg)

# ═══════════════════════════════════════════════════════════════════════════
#  REPORT HISTORY
# ═══════════════════════════════════════════════════════════════════════════
st.markdown('<p class="section-title">Report History</p>', unsafe_allow_html=True)

if "report_history" not in st.session_state or not st.session_state["report_history"]:
    st.caption("No reports generated this session.")
else:
    history = st.session_state["report_history"]
    hist_hdr = "<div style='display:grid;grid-template-columns:3fr 1.5fr 1.2fr 1.5fr 1.2fr;gap:0.5rem;" \
               "font-size:0.8rem;font-weight:600;color:#5f5e5b;border-bottom:1px solid #c8c6c3;padding-bottom:0.4rem;margin-bottom:0.4rem;'>" \
               "<span>Filename</span><span>Period</span><span>Format</span><span>Generated</span><span></span></div>"
    st.markdown(hist_hdr, unsafe_allow_html=True)
    for i, entry in enumerate(history):
        c1, c2, c3, c4, c5 = st.columns([3, 1.5, 1.2, 1.5, 1.2])
        c1.write(f"`{entry['fname']}`")
        c2.write(entry["period"])
        c3.write(f"{entry['format']} · {entry['size_kb']:.0f} KB")
        c4.write(entry["generated_at"])
        with c5:
            st.download_button(
                label="↓ Download",
                data=entry["bytes"],
                file_name=entry["fname"],
                mime=entry["mime"],
                key=f"hist_dl_{i}",
                use_container_width=True,
            )
    st.write("")
    if st.button("Clear History", key="clear_history"):
        st.session_state["report_history"] = []
        st.rerun()


# ═══════════════════════════════════════════════════════════════════════════
#  FOOTER
# ═══════════════════════════════════════════════════════════════════════════
st.markdown("""
<div style='margin-top: 4rem; padding-top: 1rem; border-top: 1px solid #c8c6c3; color: #888581; font-size: 0.8rem;'>
    For official use only. Tamil Nadu FibreNet Corporation.
</div>
""", unsafe_allow_html=True)